import { z } from "zod";

const baseProductSchema = z.object({
  name: z.string().min(1, "Name is required"),
  brand: z.string().min(1, "Brand is required"),
  model_name: z.string().optional(),
  price: z.number().min(0, "Price must be greater than 0"),
  display_specs: z.string().min(1, "Display specs are required"),
  processor: z.string().min(1, "Processor is required"),
  ram: z.string().optional(),
  storage: z.string().optional(),
  battery: z.string().min(1, "Battery specs are required"),
  os: z.string().optional(),
  color: z.string().optional(),
  image_url: z.string().optional(),
  gallery_images: z.array(z.string()).optional(),
});

export const mobileProductSchema = baseProductSchema.extend({
  camera: z.string().min(1, "Camera specs are required"),
  front_camera: z.string().optional(),
  chipset: z.string().optional(),
  charging_specs: z.string().optional(),
  screen_size: z.string().optional(),
  resolution: z.string().optional(),
  launch_date: z.string().optional(),
  release_date: z.string().optional(),
  custom_ui: z.string().optional(),
  software_support: z.string().optional(),
  cpu: z.string().optional(),
  architecture: z.string().optional(),
  fabrication: z.string().optional(),
  ram_type: z.string().optional(),
  display_type: z.string().optional(),
  aspect_ratio: z.string().optional(),
  pixel_density: z.string().optional(),
  screen_protection: z.string().optional(),
  bezel_less: z.boolean().optional(),
  touch_screen: z.boolean().optional(),
  peak_brightness: z.string().optional(),
  hdr_support: z.string().optional(),
  refresh_rate: z.string().optional(),
  height: z.string().optional(),
  width: z.string().optional(),
  thickness: z.string().optional(),
  weight: z.string().optional(),
  build_material: z.string().optional(),
  waterproof: z.string().optional(),
  ruggedness: z.string().optional(),
  camera_setup: z.string().optional(),
  camera_autofocus: z.boolean().optional(),
  camera_ois: z.boolean().optional(),
  camera_flash: z.string().optional(),
  camera_modes: z.string().optional(),
  video_recording: z.string().optional(),
  front_camera_setup: z.string().optional(),
  front_camera_video: z.string().optional(),
  wlan: z.string().optional(),
  bluetooth: z.string().optional(),
  nfc: z.string().optional(),
  positioning: z.string().optional(),
  usb: z.string().optional(),
  network_technology: z.string().optional(),
  network_2g_bands: z.string().optional(),
  network_3g_bands: z.string().optional(),
  network_4g_bands: z.string().optional(),
  network_5g_bands: z.string().optional(),
  network_speed: z.string().optional(),
  loudspeaker: z.string().optional(),
  audio_jack: z.string().optional(),
  sensors: z.string().optional(),
  models: z.string().optional(),
});

export const laptopProductSchema = baseProductSchema.extend({
  graphics: z.string().optional(),
  ports: z.string().optional(),
});

export type ProductFormData = z.infer<typeof mobileProductSchema> | z.infer<typeof laptopProductSchema>;