// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zagbpidcyqwyorhdbvlv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InphZ2JwaWRjeXF3eW9yaGRidmx2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ3Nzk2NzksImV4cCI6MjA1MDM1NTY3OX0.dcAoBSmE8INBTaLT2aeFpYvivm6K1R8SOxhzXalR1GU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);