// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lhrfrtjstlwdhepjgero.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxocmZydGpzdGx3ZGhlcGpnZXJvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzQ0NTgxMjgsImV4cCI6MjA1MDAzNDEyOH0.j0FiWJHdYUNaYufz-tALuSMwvoM_XgDZ_3vQKw_Yg74";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);